### PR TITLE
new Hook: useQueryParamState

### PR DESCRIPTION
**Pull request by gustavo-salazar**
Reflect changes in the URL query parameters in a state variable

I included the biome stuff, but the BiomeSelector is missing a prop for initial value

### CODE REVIEW

**Comment by SandyRogers** [comment]
This looks great, I tried it a bit. Nice that it uses the native `URLSearchParams` 👍 
Couple of ponders about state management, now that I've tried using it.

The only issue I see is that most of the time we have some component updating a state, and then just try to mirror that into the Search Params so the URL is up to date. Usually, we only read the Search Params to set some initial state.

This is usually fine; except when a few state changes need to be synchronised.
Example: table component with pagination control, plus a filter component that changes the data in the table.
- State is filter=badger, page=7.
- Change filter to wombat.
- Page must be reset to 1 _before_ data is refetched (in case there are <7 pages of wombats).

In a normal `useState` scenario, you could just put the parameters that need to be synced into a single state object (`tableState`). That will be kind of ugly in the Search Params!

Of the various options like adding a debounce to data fetches, changing to a "lazy" pattern of data fetching etc... I think it is probably fine to just stay like this and design better component boundaries so that these synch'd param changes aren't needed.

What do you reckon @gustavo-salazar ?

**Comment by gustavo-salazar** [comment]
I see your point.
What if we extend `useQueryParamState` into `useQueryParametersState` so it received multiple parameters. Maybe an object of the QueryParameters, and their default values. Something like: 

```javascript
const [parameters, setParameters] = useQueryParametersState({
  filter: '',
  page: 1,
})

console.log(parameters.page); // => 1 

setParameters({filter: 'badger'});
console.log(parameters); // => {page:1, filter: 'badger'}
setParameters({page: 7});
console.log(parameters); // => {page:7, filter: 'badger'}

setParameters({filter: 'wombat', page: 1});
console.log(parameters); // => {filter: 'wombat', page: 1}
```
I mean you would still need into set the page, but at least it would be in the same state which might be cleaner.

**Comment by SandyRogers** [comment]
Nice; having (the object to use) a single object as the state will fix this. I suppose you just need to be able to map from expanded url parameters back into the object somehow? So that URLs still look nice as `?page=1&filter=badger`. 

We should remember there is an edge case where you have two `useQueryParametersState`s which share a parameter key I suppose:
```js
const [parameters, setParameters] = useQueryParametersState({
  filter: 'badger',
  page: 1,
})
const [otherParameters, setOtherParameters] = useQueryParametersState({
  book: 'Wind In The Willows',
  page: 10,
})
```
My suggestion is we just allow such clashes, and they will end up with the same value but probably through some race condition :) The alternatives seem to be (1) ugly URLs with encoded objects; (2) somehow namespacing the search params to avoid clashes.

---

Separate suggestion around the setting of parameters...
> ```js
> setParameters({filter: 'badger'});
> console.log(parameters); // => {page:1, filter: 'badger'}
> setParameters({page: 7});
> console.log(parameters); // => {page:7, filter: 'badger'}
> ```

Maybe `setParameters` should work like `setState` in that it overwrites the **entire** state; so we would use spread operators to preserve the presence and value of other items in the object:
```js
setParameters({...parameters, filter: 'badger'});
console.log(parameters); // => {page:1, filter: 'badger'}
setParameters({page: 7});
console.log(parameters); // => {page:7}
```

**Comment by gustavo-salazar** [comment]
OK, so I think I got the hook to work as we wanted it, I implemented the suggested changes and all seems to work.
BTW, you read my mind about having `initialPage` on the Table, but can you also add `initialOrder`, which is missing to be able to recover the whole status of the table.

There is also another issue where `pageIndex` and `parameters.page` are out of sync. To replicate, go to any page(e.g. page 4), and then click in *Browse data* from the main menu. That link should take to the browse page without any URL parameters, sort of a _de-facto_ Clear All. This however is not working, the URL changes temporarily removing all the parameters, but the table still shows the previous page(e.g. 4). After debugging I notice that `fetchPage` was called, but `pageIndex` was still on `3`. Could you please have a look at that?

**Pull request merged**
